### ISSUE TITLE
Not updating for new python distributions

### ISSUE THREAD

**Issue by JesterEE** [conda-forge/retrying-feedstock#2]
Looks like there is an issue preventing the builds being uploaded to anaconda even though they are being built and tested (circle, appveyor, travis).
Scanning https://anaconda.org/conda-forge/retrying/files, the only platform that has a Python3.6 file is Mac.  Looking over the build for the Windows distribution on appveyor, it looks like the BINSTAR token is either not given or not accepted for the upload: 

https://ci.appveyor.com/project/conda-forge/retrying-feedstock/build/job/gvypcl3wyxfsw3o8

```cmd
403 anaconda_upload is not set.  Not uploading wheels: []
404 Build success
```

**Comment by JesterEE** [comment]
I was a bit naive to the condaforge build process.  After doing some reading for another project I know that the CI's don't directly upload to Anaconda and condaforge does that job after the build succeeds.  Since the build looks OK, I think that the [conda-smithy needs to be rerendered](https://conda-forge.org/docs/conda_smithy.html).

Regardless, I've moved onto [tenacity](https://github.com/jd/tenacity) so this is not all that important to me in particular.  Whenever @pmlandwehr gets to it.

**Comment by pmlandwehr** [comment]
Hey! Sorry about being slow on this - regenerating now!

**Comment by JesterEE** [comment]
Looks like that did it!  Closing
